create table public.tasks
(
    id          int           not null generated by default as identity primary key,
    priority    int           not null,
    description varchar(2000) not null,
    employee_id int           not null,
    foreign key (employee_id) REFERENCES public.employees (id)
);

